/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "jabra-generated.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  guint use_gvariant : 1;
  guint emits_changed_signal : 1;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface com.github.borgoat.Jabra1.Manager
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:gbjManager
 * @title: gbjManager
 * @short_description: Generated C code for the com.github.borgoat.Jabra1.Manager D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Manager.top_of_page">com.github.borgoat.Jabra1.Manager</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.github.borgoat.Jabra1.Manager ---- */

static const _ExtendedGDBusArgInfo _gbj_manager_signal_info_device_attached_ARG_device =
{
  {
    -1,
    (gchar *) "device",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _gbj_manager_signal_info_device_attached_ARG_pointers[] =
{
  &_gbj_manager_signal_info_device_attached_ARG_device.parent_struct,
  NULL
};

static const _ExtendedGDBusSignalInfo _gbj_manager_signal_info_device_attached =
{
  {
    -1,
    (gchar *) "DeviceAttached",
    (GDBusArgInfo **) &_gbj_manager_signal_info_device_attached_ARG_pointers,
    NULL
  },
  "device-attached"
};

static const _ExtendedGDBusArgInfo _gbj_manager_signal_info_device_removed_ARG_device_id =
{
  {
    -1,
    (gchar *) "device_id",
    (gchar *) "q",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _gbj_manager_signal_info_device_removed_ARG_pointers[] =
{
  &_gbj_manager_signal_info_device_removed_ARG_device_id.parent_struct,
  NULL
};

static const _ExtendedGDBusSignalInfo _gbj_manager_signal_info_device_removed =
{
  {
    -1,
    (gchar *) "DeviceRemoved",
    (GDBusArgInfo **) &_gbj_manager_signal_info_device_removed_ARG_pointers,
    NULL
  },
  "device-removed"
};

static const GDBusSignalInfo * const _gbj_manager_signal_info_pointers[] =
{
  &_gbj_manager_signal_info_device_attached.parent_struct,
  &_gbj_manager_signal_info_device_removed.parent_struct,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _gbj_manager_interface_info =
{
  {
    -1,
    (gchar *) "com.github.borgoat.Jabra1.Manager",
    NULL,
    (GDBusSignalInfo **) &_gbj_manager_signal_info_pointers,
    NULL,
    NULL
  },
  "manager",
};


/**
 * gbj_manager_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Manager.top_of_page">com.github.borgoat.Jabra1.Manager</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
gbj_manager_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_gbj_manager_interface_info.parent_struct;
}

/**
 * gbj_manager_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #gbjManager interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
gbj_manager_override_properties (GObjectClass *klass G_GNUC_UNUSED, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * gbjManager:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Manager.top_of_page">com.github.borgoat.Jabra1.Manager</link>.
 */

/**
 * gbjManagerIface:
 * @parent_iface: The parent interface.
 * @device_attached: Handler for the #gbjManager::device-attached signal.
 * @device_removed: Handler for the #gbjManager::device-removed signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Manager.top_of_page">com.github.borgoat.Jabra1.Manager</link>.
 */

typedef gbjManagerIface gbjManagerInterface;
G_DEFINE_INTERFACE (gbjManager, gbj_manager, G_TYPE_OBJECT)

static void
gbj_manager_default_init (gbjManagerIface *iface)
{
  /* GObject signals for received D-Bus signals: */
  /**
   * gbjManager::device-attached:
   * @object: A #gbjManager.
   * @arg_device: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-com-github-borgoat-Jabra1-Manager.DeviceAttached">"DeviceAttached"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("device-attached",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (gbjManagerIface, device_attached),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * gbjManager::device-removed:
   * @object: A #gbjManager.
   * @arg_device_id: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-com-github-borgoat-Jabra1-Manager.DeviceRemoved">"DeviceRemoved"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("device-removed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (gbjManagerIface, device_removed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_UINT);

}

/**
 * gbj_manager_emit_device_attached:
 * @object: A #gbjManager.
 * @arg_device: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-com-github-borgoat-Jabra1-Manager.DeviceAttached">"DeviceAttached"</link> D-Bus signal.
 */
void
gbj_manager_emit_device_attached (
    gbjManager *object,
    const gchar *arg_device)
{
  g_signal_emit_by_name (object, "device-attached", arg_device);
}

/**
 * gbj_manager_emit_device_removed:
 * @object: A #gbjManager.
 * @arg_device_id: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-com-github-borgoat-Jabra1-Manager.DeviceRemoved">"DeviceRemoved"</link> D-Bus signal.
 */
void
gbj_manager_emit_device_removed (
    gbjManager *object,
    guint16 arg_device_id)
{
  g_signal_emit_by_name (object, "device-removed", arg_device_id);
}

/* ------------------------------------------------------------------------ */

/**
 * gbjManagerProxy:
 *
 * The #gbjManagerProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * gbjManagerProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #gbjManagerProxy.
 */

struct _gbjManagerProxyPrivate
{
  GData *qdata;
};

static void gbj_manager_proxy_iface_init (gbjManagerIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (gbjManagerProxy, gbj_manager_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (gbjManagerProxy)
                         G_IMPLEMENT_INTERFACE (GBJ_TYPE_MANAGER, gbj_manager_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (gbjManagerProxy, gbj_manager_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (GBJ_TYPE_MANAGER, gbj_manager_proxy_iface_init))

#endif
static void
gbj_manager_proxy_finalize (GObject *object)
{
  gbjManagerProxy *proxy = GBJ_MANAGER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (gbj_manager_proxy_parent_class)->finalize (object);
}

static void
gbj_manager_proxy_get_property (GObject      *object G_GNUC_UNUSED,
  guint         prop_id G_GNUC_UNUSED,
  GValue       *value G_GNUC_UNUSED,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
gbj_manager_proxy_set_property (GObject      *object G_GNUC_UNUSED,
  guint         prop_id G_GNUC_UNUSED,
  const GValue *value G_GNUC_UNUSED,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
gbj_manager_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_gbj_manager_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], GBJ_TYPE_MANAGER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GBJ_TYPE_MANAGER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
gbj_manager_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  gbjManagerProxy *proxy = GBJ_MANAGER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gbj_manager_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gbj_manager_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
gbj_manager_proxy_init (gbjManagerProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = gbj_manager_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, GBJ_TYPE_MANAGER_PROXY, gbjManagerProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), gbj_manager_interface_info ());
}

static void
gbj_manager_proxy_class_init (gbjManagerProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = gbj_manager_proxy_finalize;
  gobject_class->get_property = gbj_manager_proxy_get_property;
  gobject_class->set_property = gbj_manager_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = gbj_manager_proxy_g_signal;
  proxy_class->g_properties_changed = gbj_manager_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (gbjManagerProxyPrivate));
#endif
}

static void
gbj_manager_proxy_iface_init (gbjManagerIface *iface G_GNUC_UNUSED)
{
}

/**
 * gbj_manager_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Manager.top_of_page">com.github.borgoat.Jabra1.Manager</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call gbj_manager_proxy_new_finish() to get the result of the operation.
 *
 * See gbj_manager_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
gbj_manager_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GBJ_TYPE_MANAGER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.github.borgoat.Jabra1.Manager", NULL);
}

/**
 * gbj_manager_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gbj_manager_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gbj_manager_proxy_new().
 *
 * Returns: (transfer full) (type gbjManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
gbjManager *
gbj_manager_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GBJ_MANAGER (ret);
  else
    return NULL;
}

/**
 * gbj_manager_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Manager.top_of_page">com.github.borgoat.Jabra1.Manager</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gbj_manager_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type gbjManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
gbjManager *
gbj_manager_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GBJ_TYPE_MANAGER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.github.borgoat.Jabra1.Manager", NULL);
  if (ret != NULL)
    return GBJ_MANAGER (ret);
  else
    return NULL;
}


/**
 * gbj_manager_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like gbj_manager_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call gbj_manager_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See gbj_manager_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
gbj_manager_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GBJ_TYPE_MANAGER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.github.borgoat.Jabra1.Manager", NULL);
}

/**
 * gbj_manager_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gbj_manager_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gbj_manager_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type gbjManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
gbjManager *
gbj_manager_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GBJ_MANAGER (ret);
  else
    return NULL;
}

/**
 * gbj_manager_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like gbj_manager_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gbj_manager_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type gbjManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
gbjManager *
gbj_manager_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GBJ_TYPE_MANAGER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.github.borgoat.Jabra1.Manager", NULL);
  if (ret != NULL)
    return GBJ_MANAGER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * gbjManagerSkeleton:
 *
 * The #gbjManagerSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * gbjManagerSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #gbjManagerSkeleton.
 */

struct _gbjManagerSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_gbj_manager_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  gbjManagerSkeleton *skeleton = GBJ_MANAGER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], GBJ_TYPE_MANAGER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GBJ_TYPE_MANAGER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_gbj_manager_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  gbjManagerSkeleton *skeleton = GBJ_MANAGER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gbj_manager_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_gbj_manager_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  gbjManagerSkeleton *skeleton = GBJ_MANAGER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gbj_manager_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _gbj_manager_skeleton_vtable =
{
  _gbj_manager_skeleton_handle_method_call,
  _gbj_manager_skeleton_handle_get_property,
  _gbj_manager_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
gbj_manager_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return gbj_manager_interface_info ();
}

static GDBusInterfaceVTable *
gbj_manager_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_gbj_manager_skeleton_vtable;
}

static GVariant *
gbj_manager_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  gbjManagerSkeleton *skeleton = GBJ_MANAGER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_gbj_manager_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _gbj_manager_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _gbj_manager_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _gbj_manager_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.github.borgoat.Jabra1.Manager", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
gbj_manager_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton G_GNUC_UNUSED)
{
}

static void
_gbj_manager_on_signal_device_attached (
    gbjManager *object,
    const gchar *arg_device)
{
  gbjManagerSkeleton *skeleton = GBJ_MANAGER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(s)",
                   arg_device));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.github.borgoat.Jabra1.Manager", "DeviceAttached",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_gbj_manager_on_signal_device_removed (
    gbjManager *object,
    guint16 arg_device_id)
{
  gbjManagerSkeleton *skeleton = GBJ_MANAGER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(q)",
                   arg_device_id));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.github.borgoat.Jabra1.Manager", "DeviceRemoved",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void gbj_manager_skeleton_iface_init (gbjManagerIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (gbjManagerSkeleton, gbj_manager_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (gbjManagerSkeleton)
                         G_IMPLEMENT_INTERFACE (GBJ_TYPE_MANAGER, gbj_manager_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (gbjManagerSkeleton, gbj_manager_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (GBJ_TYPE_MANAGER, gbj_manager_skeleton_iface_init))

#endif
static void
gbj_manager_skeleton_finalize (GObject *object)
{
  gbjManagerSkeleton *skeleton = GBJ_MANAGER_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (gbj_manager_skeleton_parent_class)->finalize (object);
}

static void
gbj_manager_skeleton_init (gbjManagerSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = gbj_manager_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, GBJ_TYPE_MANAGER_SKELETON, gbjManagerSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
gbj_manager_skeleton_class_init (gbjManagerSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = gbj_manager_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = gbj_manager_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = gbj_manager_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = gbj_manager_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = gbj_manager_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (gbjManagerSkeletonPrivate));
#endif
}

static void
gbj_manager_skeleton_iface_init (gbjManagerIface *iface)
{
  iface->device_attached = _gbj_manager_on_signal_device_attached;
  iface->device_removed = _gbj_manager_on_signal_device_removed;
}

/**
 * gbj_manager_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Manager.top_of_page">com.github.borgoat.Jabra1.Manager</link>.
 *
 * Returns: (transfer full) (type gbjManagerSkeleton): The skeleton object.
 */
gbjManager *
gbj_manager_skeleton_new (void)
{
  return GBJ_MANAGER (g_object_new (GBJ_TYPE_MANAGER_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for interface com.github.borgoat.Jabra1.Device
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:gbjDevice
 * @title: gbjDevice
 * @short_description: Generated C code for the com.github.borgoat.Jabra1.Device D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Device.top_of_page">com.github.borgoat.Jabra1.Device</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.github.borgoat.Jabra1.Device ---- */

static const _ExtendedGDBusPropertyInfo _gbj_device_property_info_device_id =
{
  {
    -1,
    (gchar *) "device_id",
    (gchar *) "q",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "device-id",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _gbj_device_property_info_product_id =
{
  {
    -1,
    (gchar *) "product_id",
    (gchar *) "q",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "product-id",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _gbj_device_property_info_vendor_id =
{
  {
    -1,
    (gchar *) "vendor_id",
    (gchar *) "q",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "vendor-id",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _gbj_device_property_info_device_name =
{
  {
    -1,
    (gchar *) "device_name",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "device-name",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _gbj_device_property_info_usb_device_path =
{
  {
    -1,
    (gchar *) "usb_device_path",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "usb-device-path",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _gbj_device_property_info_is_dongle =
{
  {
    -1,
    (gchar *) "is_dongle",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "is-dongle",
  FALSE,
  TRUE
};

static const GDBusPropertyInfo * const _gbj_device_property_info_pointers[] =
{
  &_gbj_device_property_info_device_id.parent_struct,
  &_gbj_device_property_info_product_id.parent_struct,
  &_gbj_device_property_info_vendor_id.parent_struct,
  &_gbj_device_property_info_device_name.parent_struct,
  &_gbj_device_property_info_usb_device_path.parent_struct,
  &_gbj_device_property_info_is_dongle.parent_struct,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _gbj_device_interface_info =
{
  {
    -1,
    (gchar *) "com.github.borgoat.Jabra1.Device",
    NULL,
    NULL,
    (GDBusPropertyInfo **) &_gbj_device_property_info_pointers,
    NULL
  },
  "device",
};


/**
 * gbj_device_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Device.top_of_page">com.github.borgoat.Jabra1.Device</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
gbj_device_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_gbj_device_interface_info.parent_struct;
}

/**
 * gbj_device_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #gbjDevice interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
gbj_device_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "device-id");
  g_object_class_override_property (klass, property_id_begin++, "product-id");
  g_object_class_override_property (klass, property_id_begin++, "vendor-id");
  g_object_class_override_property (klass, property_id_begin++, "device-name");
  g_object_class_override_property (klass, property_id_begin++, "usb-device-path");
  g_object_class_override_property (klass, property_id_begin++, "is-dongle");
  return property_id_begin - 1;
}



/**
 * gbjDevice:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Device.top_of_page">com.github.borgoat.Jabra1.Device</link>.
 */

/**
 * gbjDeviceIface:
 * @parent_iface: The parent interface.
 * @get_device_id: Getter for the #gbjDevice:device-id property.
 * @get_device_name: Getter for the #gbjDevice:device-name property.
 * @get_is_dongle: Getter for the #gbjDevice:is-dongle property.
 * @get_product_id: Getter for the #gbjDevice:product-id property.
 * @get_usb_device_path: Getter for the #gbjDevice:usb-device-path property.
 * @get_vendor_id: Getter for the #gbjDevice:vendor-id property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Device.top_of_page">com.github.borgoat.Jabra1.Device</link>.
 */

typedef gbjDeviceIface gbjDeviceInterface;
G_DEFINE_INTERFACE (gbjDevice, gbj_device, G_TYPE_OBJECT)

static void
gbj_device_default_init (gbjDeviceIface *iface)
{
  /* GObject properties for D-Bus properties: */
  /**
   * gbjDevice:device-id:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.device_id">"device_id"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_uint ("device-id", "device_id", "device_id", 0, G_MAXUINT16, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * gbjDevice:product-id:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.product_id">"product_id"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_uint ("product-id", "product_id", "product_id", 0, G_MAXUINT16, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * gbjDevice:vendor-id:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.vendor_id">"vendor_id"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_uint ("vendor-id", "vendor_id", "vendor_id", 0, G_MAXUINT16, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * gbjDevice:device-name:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.device_name">"device_name"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("device-name", "device_name", "device_name", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * gbjDevice:usb-device-path:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.usb_device_path">"usb_device_path"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("usb-device-path", "usb_device_path", "usb_device_path", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * gbjDevice:is-dongle:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.is_dongle">"is_dongle"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("is-dongle", "is_dongle", "is_dongle", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * gbj_device_get_device_id: (skip)
 * @object: A #gbjDevice.
 *
 * Gets the value of the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.device_id">"device_id"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
guint16 
gbj_device_get_device_id (gbjDevice *object)
{
  return GBJ_DEVICE_GET_IFACE (object)->get_device_id (object);
}

/**
 * gbj_device_set_device_id: (skip)
 * @object: A #gbjDevice.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.device_id">"device_id"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gbj_device_set_device_id (gbjDevice *object, guint16 value)
{
  g_object_set (G_OBJECT (object), "device-id", value, NULL);
}

/**
 * gbj_device_get_product_id: (skip)
 * @object: A #gbjDevice.
 *
 * Gets the value of the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.product_id">"product_id"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
guint16 
gbj_device_get_product_id (gbjDevice *object)
{
  return GBJ_DEVICE_GET_IFACE (object)->get_product_id (object);
}

/**
 * gbj_device_set_product_id: (skip)
 * @object: A #gbjDevice.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.product_id">"product_id"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gbj_device_set_product_id (gbjDevice *object, guint16 value)
{
  g_object_set (G_OBJECT (object), "product-id", value, NULL);
}

/**
 * gbj_device_get_vendor_id: (skip)
 * @object: A #gbjDevice.
 *
 * Gets the value of the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.vendor_id">"vendor_id"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
guint16 
gbj_device_get_vendor_id (gbjDevice *object)
{
  return GBJ_DEVICE_GET_IFACE (object)->get_vendor_id (object);
}

/**
 * gbj_device_set_vendor_id: (skip)
 * @object: A #gbjDevice.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.vendor_id">"vendor_id"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gbj_device_set_vendor_id (gbjDevice *object, guint16 value)
{
  g_object_set (G_OBJECT (object), "vendor-id", value, NULL);
}

/**
 * gbj_device_get_device_name: (skip)
 * @object: A #gbjDevice.
 *
 * Gets the value of the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.device_name">"device_name"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use gbj_device_dup_device_name() if on another thread.
 *
 * Returns: (transfer none) (nullable): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
gbj_device_get_device_name (gbjDevice *object)
{
  return GBJ_DEVICE_GET_IFACE (object)->get_device_name (object);
}

/**
 * gbj_device_dup_device_name: (skip)
 * @object: A #gbjDevice.
 *
 * Gets a copy of the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.device_name">"device_name"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full) (nullable): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
gbj_device_dup_device_name (gbjDevice *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "device-name", &value, NULL);
  return value;
}

/**
 * gbj_device_set_device_name: (skip)
 * @object: A #gbjDevice.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.device_name">"device_name"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gbj_device_set_device_name (gbjDevice *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "device-name", value, NULL);
}

/**
 * gbj_device_get_usb_device_path: (skip)
 * @object: A #gbjDevice.
 *
 * Gets the value of the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.usb_device_path">"usb_device_path"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use gbj_device_dup_usb_device_path() if on another thread.
 *
 * Returns: (transfer none) (nullable): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
gbj_device_get_usb_device_path (gbjDevice *object)
{
  return GBJ_DEVICE_GET_IFACE (object)->get_usb_device_path (object);
}

/**
 * gbj_device_dup_usb_device_path: (skip)
 * @object: A #gbjDevice.
 *
 * Gets a copy of the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.usb_device_path">"usb_device_path"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full) (nullable): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
gbj_device_dup_usb_device_path (gbjDevice *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "usb-device-path", &value, NULL);
  return value;
}

/**
 * gbj_device_set_usb_device_path: (skip)
 * @object: A #gbjDevice.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.usb_device_path">"usb_device_path"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gbj_device_set_usb_device_path (gbjDevice *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "usb-device-path", value, NULL);
}

/**
 * gbj_device_get_is_dongle: (skip)
 * @object: A #gbjDevice.
 *
 * Gets the value of the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.is_dongle">"is_dongle"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
gbj_device_get_is_dongle (gbjDevice *object)
{
  return GBJ_DEVICE_GET_IFACE (object)->get_is_dongle (object);
}

/**
 * gbj_device_set_is_dongle: (skip)
 * @object: A #gbjDevice.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-github-borgoat-Jabra1-Device.is_dongle">"is_dongle"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gbj_device_set_is_dongle (gbjDevice *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "is-dongle", value, NULL);
}

/* ------------------------------------------------------------------------ */

/**
 * gbjDeviceProxy:
 *
 * The #gbjDeviceProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * gbjDeviceProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #gbjDeviceProxy.
 */

struct _gbjDeviceProxyPrivate
{
  GData *qdata;
};

static void gbj_device_proxy_iface_init (gbjDeviceIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (gbjDeviceProxy, gbj_device_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (gbjDeviceProxy)
                         G_IMPLEMENT_INTERFACE (GBJ_TYPE_DEVICE, gbj_device_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (gbjDeviceProxy, gbj_device_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (GBJ_TYPE_DEVICE, gbj_device_proxy_iface_init))

#endif
static void
gbj_device_proxy_finalize (GObject *object)
{
  gbjDeviceProxy *proxy = GBJ_DEVICE_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (gbj_device_proxy_parent_class)->finalize (object);
}

static void
gbj_device_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 6);
  info = (const _ExtendedGDBusPropertyInfo *) _gbj_device_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
gbj_device_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface com.github.borgoat.Jabra1.Device: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
gbj_device_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 6);
  info = (const _ExtendedGDBusPropertyInfo *) _gbj_device_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "com.github.borgoat.Jabra1.Device", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) gbj_device_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
gbj_device_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_gbj_device_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], GBJ_TYPE_DEVICE);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GBJ_TYPE_DEVICE);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
gbj_device_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  gbjDeviceProxy *proxy = GBJ_DEVICE_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gbj_device_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gbj_device_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static guint16 
gbj_device_proxy_get_device_id (gbjDevice *object)
{
  gbjDeviceProxy *proxy = GBJ_DEVICE_PROXY (object);
  GVariant *variant;
  guint16 value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "device_id");
  if (variant != NULL)
    {
      value = g_variant_get_uint16 (variant);
      g_variant_unref (variant);
    }
  return value;
}

static guint16 
gbj_device_proxy_get_product_id (gbjDevice *object)
{
  gbjDeviceProxy *proxy = GBJ_DEVICE_PROXY (object);
  GVariant *variant;
  guint16 value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "product_id");
  if (variant != NULL)
    {
      value = g_variant_get_uint16 (variant);
      g_variant_unref (variant);
    }
  return value;
}

static guint16 
gbj_device_proxy_get_vendor_id (gbjDevice *object)
{
  gbjDeviceProxy *proxy = GBJ_DEVICE_PROXY (object);
  GVariant *variant;
  guint16 value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "vendor_id");
  if (variant != NULL)
    {
      value = g_variant_get_uint16 (variant);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
gbj_device_proxy_get_device_name (gbjDevice *object)
{
  gbjDeviceProxy *proxy = GBJ_DEVICE_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "device_name");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
gbj_device_proxy_get_usb_device_path (gbjDevice *object)
{
  gbjDeviceProxy *proxy = GBJ_DEVICE_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "usb_device_path");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
gbj_device_proxy_get_is_dongle (gbjDevice *object)
{
  gbjDeviceProxy *proxy = GBJ_DEVICE_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "is_dongle");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
gbj_device_proxy_init (gbjDeviceProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = gbj_device_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, GBJ_TYPE_DEVICE_PROXY, gbjDeviceProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), gbj_device_interface_info ());
}

static void
gbj_device_proxy_class_init (gbjDeviceProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = gbj_device_proxy_finalize;
  gobject_class->get_property = gbj_device_proxy_get_property;
  gobject_class->set_property = gbj_device_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = gbj_device_proxy_g_signal;
  proxy_class->g_properties_changed = gbj_device_proxy_g_properties_changed;

  gbj_device_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (gbjDeviceProxyPrivate));
#endif
}

static void
gbj_device_proxy_iface_init (gbjDeviceIface *iface)
{
  iface->get_device_id = gbj_device_proxy_get_device_id;
  iface->get_product_id = gbj_device_proxy_get_product_id;
  iface->get_vendor_id = gbj_device_proxy_get_vendor_id;
  iface->get_device_name = gbj_device_proxy_get_device_name;
  iface->get_usb_device_path = gbj_device_proxy_get_usb_device_path;
  iface->get_is_dongle = gbj_device_proxy_get_is_dongle;
}

/**
 * gbj_device_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Device.top_of_page">com.github.borgoat.Jabra1.Device</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call gbj_device_proxy_new_finish() to get the result of the operation.
 *
 * See gbj_device_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
gbj_device_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GBJ_TYPE_DEVICE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.github.borgoat.Jabra1.Device", NULL);
}

/**
 * gbj_device_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gbj_device_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gbj_device_proxy_new().
 *
 * Returns: (transfer full) (type gbjDeviceProxy): The constructed proxy object or %NULL if @error is set.
 */
gbjDevice *
gbj_device_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GBJ_DEVICE (ret);
  else
    return NULL;
}

/**
 * gbj_device_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Device.top_of_page">com.github.borgoat.Jabra1.Device</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gbj_device_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type gbjDeviceProxy): The constructed proxy object or %NULL if @error is set.
 */
gbjDevice *
gbj_device_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GBJ_TYPE_DEVICE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.github.borgoat.Jabra1.Device", NULL);
  if (ret != NULL)
    return GBJ_DEVICE (ret);
  else
    return NULL;
}


/**
 * gbj_device_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like gbj_device_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call gbj_device_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See gbj_device_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
gbj_device_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GBJ_TYPE_DEVICE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.github.borgoat.Jabra1.Device", NULL);
}

/**
 * gbj_device_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gbj_device_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gbj_device_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type gbjDeviceProxy): The constructed proxy object or %NULL if @error is set.
 */
gbjDevice *
gbj_device_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GBJ_DEVICE (ret);
  else
    return NULL;
}

/**
 * gbj_device_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like gbj_device_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gbj_device_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type gbjDeviceProxy): The constructed proxy object or %NULL if @error is set.
 */
gbjDevice *
gbj_device_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GBJ_TYPE_DEVICE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.github.borgoat.Jabra1.Device", NULL);
  if (ret != NULL)
    return GBJ_DEVICE (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * gbjDeviceSkeleton:
 *
 * The #gbjDeviceSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * gbjDeviceSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #gbjDeviceSkeleton.
 */

struct _gbjDeviceSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_gbj_device_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], GBJ_TYPE_DEVICE);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GBJ_TYPE_DEVICE);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_gbj_device_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gbj_device_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_gbj_device_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gbj_device_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _gbj_device_skeleton_vtable =
{
  _gbj_device_skeleton_handle_method_call,
  _gbj_device_skeleton_handle_get_property,
  _gbj_device_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
gbj_device_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return gbj_device_interface_info ();
}

static GDBusInterfaceVTable *
gbj_device_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_gbj_device_skeleton_vtable;
}

static GVariant *
gbj_device_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_gbj_device_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _gbj_device_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _gbj_device_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _gbj_device_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.github.borgoat.Jabra1.Device", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _gbj_device_emit_changed (gpointer user_data);

static void
gbj_device_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _gbj_device_emit_changed (skeleton);
}

static void gbj_device_skeleton_iface_init (gbjDeviceIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (gbjDeviceSkeleton, gbj_device_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (gbjDeviceSkeleton)
                         G_IMPLEMENT_INTERFACE (GBJ_TYPE_DEVICE, gbj_device_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (gbjDeviceSkeleton, gbj_device_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (GBJ_TYPE_DEVICE, gbj_device_skeleton_iface_init))

#endif
static void
gbj_device_skeleton_finalize (GObject *object)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (object);
  guint n;
  for (n = 0; n < 6; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (gbj_device_skeleton_parent_class)->finalize (object);
}

static void
gbj_device_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 6);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_gbj_device_emit_changed (gpointer user_data)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "com.github.borgoat.Jabra1.Device",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_gbj_device_schedule_emit_changed (gbjDeviceSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
gbj_device_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _gbj_device_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _gbj_device_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
gbj_device_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 6);
  info = (const _ExtendedGDBusPropertyInfo *) _gbj_device_property_info_pointers[prop_id - 1];
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL &&
          info->emits_changed_signal)
        _gbj_device_schedule_emit_changed (skeleton, info, prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
gbj_device_skeleton_init (gbjDeviceSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = gbj_device_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, GBJ_TYPE_DEVICE_SKELETON, gbjDeviceSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 6);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_UINT);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_UINT);
  g_value_init (&skeleton->priv->properties[2], G_TYPE_UINT);
  g_value_init (&skeleton->priv->properties[3], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[4], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[5], G_TYPE_BOOLEAN);
}

static guint16 
gbj_device_skeleton_get_device_id (gbjDevice *object)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (object);
  guint value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_uint (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static guint16 
gbj_device_skeleton_get_product_id (gbjDevice *object)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (object);
  guint value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_uint (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static guint16 
gbj_device_skeleton_get_vendor_id (gbjDevice *object)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (object);
  guint value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_uint (&(skeleton->priv->properties[2]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
gbj_device_skeleton_get_device_name (gbjDevice *object)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[3]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
gbj_device_skeleton_get_usb_device_path (gbjDevice *object)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[4]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
gbj_device_skeleton_get_is_dongle (gbjDevice *object)
{
  gbjDeviceSkeleton *skeleton = GBJ_DEVICE_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[5]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
gbj_device_skeleton_class_init (gbjDeviceSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = gbj_device_skeleton_finalize;
  gobject_class->get_property = gbj_device_skeleton_get_property;
  gobject_class->set_property = gbj_device_skeleton_set_property;
  gobject_class->notify       = gbj_device_skeleton_notify;


  gbj_device_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = gbj_device_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = gbj_device_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = gbj_device_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = gbj_device_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (gbjDeviceSkeletonPrivate));
#endif
}

static void
gbj_device_skeleton_iface_init (gbjDeviceIface *iface)
{
  iface->get_device_id = gbj_device_skeleton_get_device_id;
  iface->get_product_id = gbj_device_skeleton_get_product_id;
  iface->get_vendor_id = gbj_device_skeleton_get_vendor_id;
  iface->get_device_name = gbj_device_skeleton_get_device_name;
  iface->get_usb_device_path = gbj_device_skeleton_get_usb_device_path;
  iface->get_is_dongle = gbj_device_skeleton_get_is_dongle;
}

/**
 * gbj_device_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-github-borgoat-Jabra1-Device.top_of_page">com.github.borgoat.Jabra1.Device</link>.
 *
 * Returns: (transfer full) (type gbjDeviceSkeleton): The skeleton object.
 */
gbjDevice *
gbj_device_skeleton_new (void)
{
  return GBJ_DEVICE (g_object_new (GBJ_TYPE_DEVICE_SKELETON, NULL));
}

